server:
  port: 8080

spring:
  application:
    name: cloud-gateway

  data:
    redis:
        host: localhost
        port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-qf3gwiu4.sql.tencentcdb.com:22289/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: GEASS001zero!

  cloud:
    loadbalancer:
      cache:
        enabled: true
    sentinel:
      datasource:
        flow-rules:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            rule-type: flow
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719
      eager: true

    gateway:
      discovery:
        locator:
            enabled: true
            lower-case-service-id: true
      routes:
        # 核心模块
        - id: cloud-core
          uri: lb://cloud-core
          predicates:
            - Path=/core/**

        # 认证中心
        - id: cloud-auth
          uri: lb://cloud-auth
          predicates:
            - Path=/auth/**

        # 用户模块
        - id: cloud-user
          uri: lb://cloud-user
          predicates:
            - Path=/user/**

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        register-enabled: true
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        import-check:
          enabled: false



