server:
  port: 8081

spring:
  application:
    name: cloud-core

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-qf3gwiu4.sql.tencentcdb.com:22289/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: GEASS001zero!

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        import-check:
          enabled: false
#        shared-configs:
#          - data-id: cloud_datasource_config_dev.yaml
#            group: DEFAULT_GROUP
#            refresh: true

dromara:
  x-file-storage: #文件存储配置
    default-platform: minio-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    minio:
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: SZJg3PM9D8pAQwV4e4iL
        secret-key: 8Nbulbkp5K5c6j79Ic7uYqHVzlR0npPofDToTnkI
        end-point: https://cloud-cdn.cloudyuan.cn
        bucket-name: cloud-test
        domain: https://cloud-cdn.cloudyuan.cn/${dromara.x-file-storage.minio[0].bucket-name}/ # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: test/ # 基础路径

sentinel:
  port: 8858
  url: 127.0.0.1



