server:
  port: 8083

spring:
  application:
    name: cloud-user

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
      config:
        server-addr: 127.0.0.1:8848
        #        file-extension: yml
        import-check:
          enabled: false